language: node_js

node_js:
  - "4.2"
  - "5.0"

# Use container-based Travis infrastructure.
sudo: false

branches:
  only:
    - master

before_install:
  # GUI for real browsers.
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

  # Install npmv3 because of postinstall bugs in npmv2:
  # See https://github.com/FormidableLabs/victory/issues/98
  - npm install -g npm@3

install:
  - npm install

script:
  - npm test
  - NODE_ENV=production node_modules/.bin/builder run build-static
  - node_modules/.bin/builder run install-selenium
  - ROWDY_SETTINGS=local.firefox node_modules/.bin/builder run test-func-static-prod
  - ROWDY_SETTINGS=local.phantomjs node_modules/.bin/builder run test-func-static-prod
